config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root "questions#index"

  resources :questions do
    resources :answers, except: [:index, :show]
  end

  post   'likes/:sgid', to: 'likes#create', as: :likes
  delete 'likes/:sgid', to: 'likes#destroy'

  direct(:embeded_answer) do |answer|
    url_for [answer.question, anchor: "answer_#{answer.id}"]
  end

  resources :search, only: :index
end

app/models/question.rb
class Question < ApplicationRecord
  include Chronology

  belongs_to :creator, class_name: "User", default: -> { Current.user }
  has_many :answers, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  validates :title, :content, presence: true

  searchkick word_middle: [:title, :content]

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_managing, only: [:edit, :update, :destroy]

  def index
    @questions = Question.reverse_chronologically.page params[:page]
  end

  def show
  end

  def new
    @question = Current.user.questions.new
  end

  def edit
    respond_to do |format|
      format.html
    end
  end

  def create
    @question = Current.user.questions.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def authorize_managing
      raise Guardian::NotAuthorizedError unless Guardian.new(Current.user, @question).can_manage?
    end

    def question_params
      params.require(:question).permit(:title, :content)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <%= form_errors form.object %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, rows: 10, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Post question", class: "btn btn-success" %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<li class="media border-bottom p-2">
  <%= user_avatar question.creator, class: "mr-2" %>
  <div class="media-body">
    <p class="d-block m-0 text-muted">
    <%= tag.small "#{question.creator.name} asked" %>
    </p>
    <%= link_to question.title, question, class: "mt-o mb-1" %>
    <small class="text-muted d-block">
      <%= question.content %>
    </small>
    <span>
    <span class="badge badge-light mt-2"><%= question.answers_count %> answers</span>
  </button>
  </div>
</li>

app/views/questions/edit.html.erb
<div class="card">
  <div class="card-body">
    <%= render 'form', question: @question %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="card">
  <div class="card-body">
    <h4 class="card-title">
      Questions
    </h4>

    <ul class="list-unstyled">
      <%= render @questions %>
    </ul>

    <%= paginate @questions %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="card">
  <div class="card-body">
    <%= render 'form', question: @question %>
  </div>
</div>

app/views/questions/show.html.erb
<article id="<%= dom_id(@question) %>" class="media mb-2">
  <div class="card card-body media-body">
    <h3><%= @question.title %></h3>
    <h6 class="mt-0 p-1 border-top border-bottom">
      <%= user_avatar @question.creator %>
      <%= @question.creator.name %>
      <small>asked at <%= local_time_ago(@question.created_at) %></small>

      <div class="actions float-right">
        <%= link_to "Edit", edit_question_path(@question), class: "text-right" if can_manage?(@question) %>
        <%= link_to "Delete", question_path(@question), method: :delete, data: { confirm: 'Are you sure?' }, class: "text-right" if can_manage?(@question) %>
      </div>
    </h6>
    <%= markdown @question.content %>

    <%= tag.div id: dom_id(@question, :likes) do %>
      <%= render "likes/likes", likeable: @question %>
    <% end %>
  </div>
</article>

<section id="answers">
  <%= render @question.answers %>
</section>

<section class="media mb-2" id="new_answer">
  <%= render "answers/form", question: @question, answer: @question.answers.new %>
</section>