config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root "questions#index"

  resources :questions do
    resources :answers, except: [:index, :show]
  end

  post   'likes/:sgid', to: 'likes#create', as: :likes
  delete 'likes/:sgid', to: 'likes#destroy'

  direct(:embeded_answer) do |answer|
    url_for [answer.question, anchor: "answer_#{answer.id}"]
  end

  resources :search, only: :index
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Chronology

  belongs_to :question, counter_cache: true
  belongs_to :creator, class_name: "User", default: -> { Current.user }
  has_many :likes, as: :likeable, dependent: :destroy

  validates :content, presence: true

  searchkick word_middle: [:content]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include QuestionScoped

  before_action :set_answer, only: [:edit, :update, :destroy]
  before_action :authorize_managing, only: [:edit, :update, :destroy]

  def create
    @answer = @question.answers.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.js
      else
        format.js { render partial: "error", status: :error }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.js
      else
        format.js { render partial: "error", status: :error }
      end
    end
  end

  def destroy
    @answer.destroy

    respond_to do |format|
      format.js
    end
  end


  private
    def answer_params
      params.require(:answer).permit(:content)
    end

    def authorize_managing
      raise Guardian::NotAuthorizedError unless Guardian.new(Current.user, @question).can_manage?
    end

    def set_answer
      @answer = @question.answers.find(params[:id])
    end
end

app/views/answers/_answer.html.erb
<article id="<%= dom_id(answer) %>" class="media mb-2">
  <%= user_avatar answer.creator, size: "24x24", class: "mr-1" %>

  <div class="card card-body media-body">
    <h6 class="mt-0">
      <%= answer.creator.name %>
      <small>posted at <%= local_time_ago(answer.created_at) %></small>

      <div class="actions float-right">
        <%= link_to "Edit", edit_question_answer_path(@question, answer), remote: true if can_manage?(answer) %>
        <%= link_to "Delete", question_answer_path(@question, answer), method: :delete, remote: true,
          data: { confirm: 'Are you sure?' }, class: "text-right" if can_manage?(answer) %>
      </div>
    </h6>

    <%= markdown answer.content %>

    <%= tag.div id: dom_id(answer, :likes) do %>
      <%= render "likes/likes", likeable: answer %>
    <% end %>
  </div>
</article>

app/views/answers/_form.html.erb
<%= user_avatar Current.user, size: "24x24", class: "mr-1" %>
<%= form_with(model: [question, answer], id: "answer-form", class: "media-body", local: false) do |form| %>
  <div class="form-group m-0 mb-1 border">
    <%= form.text_area :content, rows: 5, class: "form-control", required: true %>
  </div>

  <%= form.submit "Post Your Answer", class: "btn btn-success" %>
<% end %>

app/views/answers/create.js.erb
var answers = document.getElementById("answers");
var answer_form = document.getElementById("new_answer");

answers.innerHTML += "<%= j render("answers/answer", answer: @answer) %>";
answer_form.innerHTML = "<%= j render("answers/form", question: @question, answer: @question.answers.new) %>";

app/views/answers/destroy.js.erb
$("#answer_<%= @answer.id %>").remove();

app/views/answers/edit.js.erb
var answer = document.getElementById("answer_<%= @answer.id %>")
answer.innerHTML = "<%= j render("answers/form", question: @question, answer: @answer) %>";

app/views/answers/update.js.erb
var answer = $("#answer_<%= @answer.id %>")
answer.replaceWith("<%= j render("answers/answer", answer: @answer) %>");